OPENAI_API_KEY = "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"

USERNAME = "jurisai"
ACCESS_KEY = "jurisai"
