OPENAI_API_KEY = "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"

USERNAME = "jurisai"
ACCESS_KEY = "jurisai"
